#!/bin/bash

USER=demo
SKIP=0
if [ $# -eq 1 ]
then
	USER=$1
else
	klist > /dev/null 2> /dev/null
	if [ $? == 0 ]
	then
		SKIP=1
		echo 'Reusing existing credentials (specify username to override)'
	fi
fi

if [ $SKIP != 1 ]
then
	if [ "X$USER" = "X@" ]
	then
		echo 'Destroying Kerberos credentials'
		kdestroy
	else
		echo "Requesting Kerberos credentials for $USER@ARPA2.NET"
		kinit $USER
	fi
fi

klist
KLISTED=$?

if [ -w /etc/ldap/ldap.conf ]
then
	if [ $KLISTED == 0 ]
	then
		TRAILER='cn=gssapi,cn=auth'
	else
		TRAILER='ou=IdentityHub,o=arpa2.net,ou=InternetWide'
	fi
	
	sed -i -e 's/^BINDDN/# BINDDN/' /etc/ldap/ldap.conf
	sed -i -e 's/^# \(BINDDN.*,'"$TRAILER\)"'/\1/' /etc/ldap/ldap.conf

	echo "Updated /etc/ldap/ldap.conf with BINDDN ...,$TRAILER"
fi

